//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alms.cherry.common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationLocalization_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationLocalization_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alms.cherry.common.ApplicationLocalization_ru", typeof(ApplicationLocalization_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика.
        /// </summary>
        internal static string business_general_analytic {
            get {
                return ResourceManager.GetString("business.general.analytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        internal static string business_general_categories {
            get {
                return ResourceManager.GetString("business.general.categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string business_general_category {
            get {
                return ResourceManager.GetString("business.general.category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        internal static string business_general_employee {
            get {
                return ResourceManager.GetString("business.general.employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        internal static string business_general_employees {
            get {
                return ResourceManager.GetString("business.general.employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        internal static string business_general_orders {
            get {
                return ResourceManager.GetString("business.general.orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список товаров.
        /// </summary>
        internal static string business_general_productlist {
            get {
                return ResourceManager.GetString("business.general.productlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        internal static string business_general_products {
            get {
                return ResourceManager.GetString("business.general.products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство.
        /// </summary>
        internal static string business_general_structure {
            get {
                return ResourceManager.GetString("business.general.structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование продукта.
        /// </summary>
        internal static string business_product_edit {
            get {
                return ResourceManager.GetString("business.product.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список товаров.
        /// </summary>
        internal static string business_viewmodels_productlistviewmodel {
            get {
                return ResourceManager.GetString("business.viewmodels.productlistviewmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя или пароль.
        /// </summary>
        internal static string system_error_username_or_password_isnt_correct {
            get {
                return ResourceManager.GetString("system.error.username_or_password_isnt_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый юзер.
        /// </summary>
        internal static string system_general_add_new_user {
            get {
                return ResourceManager.GetString("system.general.add_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из системы?.
        /// </summary>
        internal static string system_general_applicationquit {
            get {
                return ResourceManager.GetString("system.general.applicationquit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string system_general_cancel {
            get {
                return ResourceManager.GetString("system.general.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string system_general_confirm {
            get {
                return ResourceManager.GetString("system.general.confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите выйти?.
        /// </summary>
        internal static string system_general_confirmationquit {
            get {
                return ResourceManager.GetString("system.general.confirmationquit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string system_general_error {
            get {
                return ResourceManager.GetString("system.general.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string system_general_exit {
            get {
                return ResourceManager.GetString("system.general.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string system_general_login {
            get {
                return ResourceManager.GetString("system.general.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        internal static string system_general_ok {
            get {
                return ResourceManager.GetString("system.general.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string system_general_password {
            get {
                return ResourceManager.GetString("system.general.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string system_general_username {
            get {
                return ResourceManager.GetString("system.general.username", resourceCulture);
            }
        }
    }
}
